[package]
name = "trap-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { workspace = true, features = ["untrusted_programs"] }
sp1-primitives = { path = "../../../crates/primitives" }
rand = "0.8.5"
