[package]
name = "memory-tester"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
sp1-zkvm = { path = "../../../../crates/zkvm/entrypoint" }
sp1-primitives = { path = "../../../../crates/primitives" }
