[package]
name = "sp1-sdk-types"
description = "Shared types for the SP1 SDK and SP1 network client"
readme = "../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
num-bigint = { workspace = true }
slop-algebra = { workspace = true }
slop-alloc = { workspace = true }
slop-basefold = { workspace = true }
slop-commit = { workspace = true }
slop-jagged = { workspace = true }
slop-multilinear = { workspace = true }
slop-sumcheck = { workspace = true }
slop-tensor = { workspace = true }
sp1-build = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-core-machine = { workspace = true }
sp1-hypercube = { workspace = true }
sp1-primitives = { workspace = true }
sp1-prover = { workspace = true }
sp1-recursion-executor = { workspace = true }
sp1-verifier = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }

[lints]
workspace = true
